#ifndef _CONSTS_H_
#define _CONSTS_H_

#define PORT "80"
#define SERVER_ROOT "./root"
#define MAX_READ_BUF 2048
#define MAX_LINE_BUF 512
#define MAX_RECV_TIMEOUT_HEAD 3
#define MAX_RECV_TIMEOUT_GET 8
#define MAX_HTTP_HDR_SIZE 512
#define MAX_REQUESTS_QUEUE_SIZE 10
#define MAX_RESPONSE_SIZE 262144

#endif